image: https://github.com/docker-library/python/blob/b99b66406ebe728fb4da64548066ad0be6582e08/3.6/stretch/Dockerfile

stage:
    - test

test:
    stage: test
    script:
        - pip install -r requirments.txt
        - python manage.py test
