image: python:3.6

stages:
    - test

before_script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - echo 'Starting before script'
  - pip install -r requirements.txt

test:
    stage: test
    script:
        - echo 'Starting the test'
        - python home_dashboard/manage.py test
