stages:
    - test

before_script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - echo 'Starting before script'
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt

test:
    stage: test
    script:
        - echo 'Starting the test'
        - python manage.py test
