#!/bin/sh
### BEGIN INIT INFO
# Provides:          home_dashboard_uwsgi
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Run the uWSGI for the home_dashboard application so NGINX can connect to it.
### END INIT INFO

RUNAS=<<the system user you created for this app>>
PIDFILE=/var/run/home_dashboard_uwsgi.pid
LOGFILE=/var/log/home_dashboard/home_dashboard_uwsgi.log <<or any other place you want for the log file - make sure your RUNAS can write to it>>

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="PATH='<<the path to you env>>:$PATH';export PATH ; uwsgi <<the path to you uwsgi config file>> &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" -s /bin/bash $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -9 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f <NAME> remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
