# Generated by Django 2.0.2 on 2018-05-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='meter_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='remark',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
