# Generated by Django 2.0.2 on 2018-05-29 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_auto_20180527_0932'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('date', 'meter')},
        ),
        migrations.AlterUniqueTogether(
            name='usage',
            unique_together={('year', 'month', 'meter')},
        ),
    ]
